
# Zainstalowanie pakietów

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biostrings", force = T)
BiocManager::install("Rsubread")
install.packages("fastqcr")
BiocManager::install("Rqc")
BiocManager::install("Rfastp")
```

# Załadowanie pakietów

```{r}
#library('GenomicAlignments')
#library('Biostrings')
```

# Sprawdzenie jakości plików fastq

```{r}
library(Rqc)
rqc(path = "fastq/", # ścieżka z plikami fastq
    pattern = ".fastq.gz",  # wzór według, które pliki mają być analizowane
    outdir = "fastqc/", # folder do zapisania raportu
    file = "rqc_kurs") # nazwa pliku html z raportem
```

```{r}
library(Rfastp)
rfastp("/path/to/folder/*.fastq", # plik do analizy
       outputFastq = "/path/to/output/folder/file_name") # ścieżka i nazwa nowego pliku fastq, po filtrowaniu i odcięciu adapterów
```

```{r}
library("fastqcr") #CRAN
fastqc_install() # instalujemy tylko za pierwszym razem
fastq.dir <- "fastq"

fastqc(fastq.dir, threads = 12) #można zmienić wartość 'threds' w zależności od komputera
```

```{r}
qc.path <- "/path/to/fastq/folder/FASTQC"
qc <- qc_aggregate(qc.path, progressbar = T)
```

```{r}
head(qc)
summary(qc)
qc_stats(qc)
qc_fails(qc, "module") # Moduły z oznaczeniem nie przeszły w wiekszosci prób
qc_problems(qc, "sample") # Proby z problemami
```

# Mapowanie

```{r}
library(Rsubread)
```

## Zbudowanie indexu genomu

```{r}
# informacje o genomie dla mm10 dla 19 chromosomu znajduja sie w pliku 'chr19.fa.gz'
# poniższa funkcja tworzy pliki indeksów z nazwami 'chr19_mm10'
buildindex(basename = "/path/to/index/folder/chr19_mm10", reference = "/path/to/folder/chr19.fa")

dir("/path/to/folder/index_subread/", pattern = "chr19") # wyswietla pliki z katalogu
```

## Mapowanie

```{r}
#mapowanie
#zmienna 'index' - należy podać nazwę, która była nadana w poprzedniej komendzie
align(index = "/path/to/index/folder/chr19_mm10", readfile1 = "/path/to/fastq/file.fastq.gz", nthreads = 8) # warto zmienić nthreads
# u mnie jeden plik fastq mapowany ok. 5 min

#mapowanie wszystkich plików fastq z katalogu
#path_to_fastq = "/path/to/fastq/"
#fastq_files = dir(path_to_fastq, pattern = ".gz")
#align(index = "/path/to/index/folder/chr19_mm10", readfile1 = paste(path_to_fastq,fastq_files, sep = ""), nthreads = 8) # warto zmienić nthreads
fastq_files <- list.files(path = "/Users/arek/Documents/xenstats/2023.11.17-18_kurs/fastq", pattern = ".fastq.gz$", full.names = T)
head(fastq_files)
align(index = "/path/to/index/folder/chr19_mm10", readfile1 = fastq_files, nthreads = 8) # warto zmienić nthreads
```

## Mapowanie unikaowych odczytów

```{r}
align(index = "/path/to/index/chr19_mm10", readfile1 = "/path/to/fastq/file.fastq.gz", unique = T, nthreads = 8,
      output_file = paste("name","unique","BAM",sep=".")) # warto zmienić nthreads

```

## Sprawdzanie jakości mapowania

```{r}
bam_files <- list.files(path = "/path/to/folder/BAM/", pattern = ".BAM$", full.names = T)
props <- propmapped(files=bam_files)
props
```

# Zliczanie odczytów

```{r}
fc <- featureCounts(bam_files, annot.ext = "Mus_musculus.GRCm39.104.gtf", isGTFAnnotationFile = TRUE, 
                    GTF.featureType = "exon", GTF.attrType = "gene_id")

# sprawdzenie struktury 'fc'
names(fc)
```

```{r}
# sprawdzenie wymiaru
dim(fc$counts)
fc$annotation
# spojrzenie na pierwsze wiersze tabelki countów

head(fc$counts) # nazwy wierszy to - Entrez gene identifiers

counts = as.data.frame(fc$counts) # tworzy data frame z odczytami
write.table(counts, file = "/path/to/save/counts.txt", sep = "\t", dec = ".") # zapisanie tabeli z odczytami
```

```{r}
fc2 <- featureCounts(bam_files, annot.inbuilt = "mm10", 
                    GTF.featureType = "exon", GTF.attrType = "gene_id")

# sprawdzenie struktury 'fc'
names(fc2)
```

#Koniec

```{r}
# sprawdzenie wersji pakietów
sessionInfo()
```